version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "${S3FrontendDeployBucket}"
    BUILD_FOLDER: "dist"
    CONFIG_FILE: "src/assets/config.json"
    CONFIG_DEFAULT_BASE_URL: "https://api-dev.somethingcode.com"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
    - echo Installing source NPM dependencies...
    - npm install
    - npm install -g @angular/cli
  build:
    commands:
    - echo Build started
    - >-
    sed -i "s|$CONFIG_DEFAULT_BASE_URL|https://${URLBackend}|g" $CONFIG_FILE
    - >-
    sed -i "s|\"s3uploadUrl\": \".*\",|\"s3uploadUrl\": \"${S3DocumentsBucketDomainName}\",|g" $CONFIG_FILE
    - >-
    sed -i "s|\"cognitoBase\": \".*\",|\"cognitoBase\": \"https://${HostedUserPoolDomainName}\",|g" $CONFIG_FILE
    - >-
    sed -i "s|\"cognitoClientId\": \".*\",|\"cognitoClientId\": \"${CognitoClientId}\",|g" $CONFIG_FILE
    - >-
    sed -i "s|\"cognitoRedirectUri\": \".*\",|\"cognitoRedirectUri\": \"https://${S3FrontendDeployBucket}/callback\",|g" $CONFIG_FILE 
    - ng build --prod
artifacts:
  files:
  - '**/*'
  base-directory: 'dist*'
  discard-paths: yes