# buildspec-api.yml
# Brian Jopling, Jan 2020
#
# Deploys code from GitHub to AWS Lambda.
# Prerequisites: CodeBuild running amazon-linux-2 AMI 2.0

version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
        - echo Starting...
  build:
    commands:
        - echo Deployment started.
        - cd ./APILambdas/
        - |
          for dirname in */
          do
            dirname=${dirname%*/}
            cd $dirname
            zip -r ${dirname}.zip *
            aws lambda update-function-code --function-name ${dirname} --zip-file fileb://${dirname}.zip || echo "Unable to update Lambda ${dirname}"
            cd ../
          done;
        - cd ..
        - cd ./NodeLambdas/
        - npm install
        - npm run build-all
        - npm run promote-all || echo "promote-all failed"
        - echo Deployment complete.
artifacts:
  files:
  - '**/*'
  discard-paths: no

