# cfn-nested-rds.yaml
# Author: Brian Jopling, Feb 2020
#
# Description:
#   Deploys components required for the RDS; namely
#   the instance itself.
#


AWSTemplateFormatVersion: "2010-09-09"
Description: Nested template for creating RDS infra.

Parameters:
  EnvVarDbPassword:
    Type: String
    Description: "DB password must be stored in SecretsManager. Provide the key name here."
    Default: "db-credentials:SecretString:password"
  EnvVarDbUser:
    Type: String
    Description: "DB username must be stored in SecretsManager. Provide the key name here."
    Default: "db-credentials:SecretString:username"

Resources:

  RDSApplicationDB:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: "buddy"
      Engine: aurora-mysql
      EngineMode: serverless
      EnableHttpEndpoint: true
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 1
        MinCapacity: 1
        SecondsUntilAutoPause: 300
      StorageEncrypted: true
      MasterUsername: !Sub "{{resolve:secretsmanager:${EnvVarDbUser}}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${EnvVarDbPassword}}}"
      DBClusterParameterGroupName: !Ref RDSApplicationDBParamGroup

  RDSApplicationDBParamGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Family: aurora-mysql5.7
      Description: "buddy-db"
      Parameters:
        group_concat_max_len: '18446744073709547519'
        wait_timeout: '31536000'

Outputs:
  RDSApplicationUrl: 
    Value: !GetAtt RDSApplicationDB.Endpoint.Address