# cfn-nested-rds.yaml
# Author: Brian Jopling, Feb 2020
#
# Description:
#   Deploys components required for the RDS; namely
#   the instance itself.
#


AWSTemplateFormatVersion: "2010-09-09"
Description: Nested template for creating RDS infra.

Parameters:
  EnvVarDbName:
    Type: String
    Description: "DB name must be stored in SecretsManager. Provide the key name here."
    Default: "db-credentials:SecretString:dbInstanceIdentifier"
  EnvVarDbPassword:
    Type: String
    Description: "DB password must be stored in SecretsManager. Provide the key name here."
    Default: "db-credentials:SecretString:password"
  EnvVarDbUser:
    Type: String
    Description: "DB username must be stored in SecretsManager. Provide the key name here."
    Default: "db-credentials:SecretString:username"

Resources:

  RDSApplicationDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Sub "{{resolve:secretsmanager:${EnvVarDbName}}}"
      AllocatedStorage: "20"
      CACertificateIdentifier: rds-ca-2019
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      EngineVersion: 5.7.22
      MasterUsername: !Sub "{{resolve:secretsmanager:${EnvVarDbUser}}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${EnvVarDbPassword}}}"
      DBParameterGroupName: !Ref RDSApplicationDBParamGroup

  RDSApplicationDBParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: mysql5.7
      Description: "buddy-db"
      Parameters:
        group_concat_max_len: '18446744073709547519'
        wait_timeout: '31536000'

Outputs:
  RDSApplicationUrl: 
    Value: !GetAtt RDSApplicationDB.Endpoint.Address