# cfn-nested-frontend-cloudfront.yaml
# Author: Brian Jopling, Feb 2020
#
# Description:
#   Deploys components required for frontend web hosting; namely the
#   CloudFront resource.
#
# Decoupled from the other frontend template because this one takes
# 30 minutes to deploy. The other frontend template is a dependency
# for other templates to start deploying, so this way the CloudFront
# distribution can be created in parallel.
#
# Usage: - Manual validation of ACM cert must be done during the deployment process.
#           Otherwise, the stack will hang.
#        - Upon completion of deployment, an Alias record must be created to point
#           the custom domain url to the CloudFront distribution.
#

AWSTemplateFormatVersion: "2010-09-09"
Description: Nested template for Frontend deployment.

Parameters:

  S3FrontendDeployBucket:
    Type: String
    Default: www.somethingcode.com
    Description: Bucket that hosts the frontend web files.

  URLFrontend:
    Type: String
    Default: "www.somethingcode.com"

  CloudFrontOriginAccessIdentity:
    Type: String
    Default: "placeholder"

Resources:

  Cert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref URLFrontend
      DomainValidationOptions:
        - DomainName: !Ref URLFrontend
          ValidationDomain: !Ref URLFrontend
      ValidationMethod: DNS

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref URLFrontend
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Ref S3FrontendDeployBucket
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !Join ['', [!Ref S3FrontendDeployBucket, '.s3.amazonaws.com']]
            Id: !Ref S3FrontendDeployBucket
            S3OriginConfig:
              OriginAccessIdentity:
                !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudFrontOriginAccessIdentity]]
        ViewerCertificate:
          AcmCertificateArn: !Ref Cert
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only
      Tags:
        - Key: Domain
          Value: !Ref URLFrontend
