# cfn-nested-ses.yaml
# Author: Brian Jopling, Mar 2020
#
# Description:
#   Deploys components required for SES; namely
#   the Invitation template.
#


AWSTemplateFormatVersion: "2010-09-09"
Description: Nested template for creating SES infra.

Parameters:
  S3OpenApiSpecBucket:
    Type: String
    Default: studybuddy-cfn-templates
    Description: Name of S3 bucket containing the OpenAPI Specification.
  URLFrontend:
    Type: String
    Default: "placeholder"
    Description: URL to access application, passed in from master template.

Resources:
  SesEmailTemplateInvitation:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: "InvitationTemplate"
        SubjectPart: "You've been invited to a group in Study Buddy!"
        TextPart: !Sub "Hello, {{invited_by_user}} wants to share their conversation with you. Use the link below to join them. https://${URLFrontend}/invitation/{{invitation_id}}"
        HtmlPart: !Sub "<h1>Hello,</h1><p>{{invited_by_user}} wants to share their conversation with you. Click the link below to join them.</p><br><a href=\"https://${URLFrontend}/invitation/{{invitation_id}}\">Join {{invited_by_user}}</a>"
  

