# cfn-master.yaml
# Author: Brian Jopling, Jan 2020
#
# Description:
#   Deploys nested templates to automate the creation of all infrastructure
#   required by StudyBuddy.
#
# Usage: - Manual validation of ACM certs must be done during the deployment process.
#           Otherwise, the stack will hang. (Two certs, one for Cognito, one for Frontend.)
#        - Upon completion of deployment, an Alias record must be created to point
#           the custom domain url to the CloudFront distribution. (Two urls, one for 
#           Cognito, one for Frontend.)
#
# Pre-requisites: Google Client ID and Client Secret must be stored in SecretsManager before deploying.
#

AWSTemplateFormatVersion: "2010-09-09"
Description: Master template for creating all StudyBuddy infra.

Parameters:
  S3InfrastructureBucket:
    Type: String
    Default: studybuddy-templates
    Description: S3 bucket containing all the CloudFormation templates & OpenAPI Spec.

Resources:
  NestedStackCognito:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-cognito.yaml"
      TimeoutInMinutes: 10

  NestedStackLambda:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-lambda.yaml"
      TimeoutInMinutes: 10

  NestedStackApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-apigw.yaml"
      TimeoutInMinutes: 10
  
  NestedStackFrontend:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-frontend.yaml"
      TimeoutInMinutes: 10
