# cfn-nested-frontend-s3.yaml
# Author: Brian Jopling, Feb 2020
#
# Description:
#   Deploys S3 components required for frontend web hosting; namely the
#   S3 Web Hosting Bucket.
#

AWSTemplateFormatVersion: "2010-09-09"
Description: Nested template for Frontend deployment.

Parameters:

  URLFrontend:
    Type: String
    Default: "www.somethingcode.com"
  S3DocumentsBucketName:
    Type: String
    Default: "placeholder"

Resources:

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI for ${URLFrontend}'

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref URLFrontend
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Domain
          Value: !Ref URLFrontend

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Join ['', ['arn:aws:s3:::', !Ref Bucket, '/*']]
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  S3DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3DocumentsBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: 
              - "*"
            AllowedMethods: 
              - "GET"
              - "PUT"
            AllowedOrigins: 
              - "*"
            MaxAge: 3000

Outputs:
  CloudFrontOriginAccessIdentity:
    Value: !Ref CloudFrontOriginAccessIdentity
  S3FrontendDeployBucket:
    Value: !Ref Bucket
  S3DocumentsBucket:
    Value: !Ref S3DocumentsBucket
  S3DocumentsBucketDomainName:
    Value: !GetAtt S3DocumentsBucket.DomainName