# cfn-nested-sagemaker.yaml
# Author: Brian Jopling, Feb 2020
#
# Description:
#   Deploys components required for the Sagemaker; namely
#   the endpoint, its configuration, and the model.
#


AWSTemplateFormatVersion: "2010-09-09"
Description: Nested template for creating SageMaker infra.

Parameters:

  S3ArtifactsBucket:
    Type: String
    Default: studybuddy-cicd-pipeline
    Description: Bucket containing the Lambda source code.

Resources:

  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - sagemaker.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: SageMakerExecutionPolicy
        PolicyDocument:
          Statement:
          - Action:
            - s3:ListBucket
            Resource: arn:aws:s3:::*
            Effect: Allow
          - Action:
            - sagemaker:InvokeEndpoint
            Resource: arn:aws:sagemaker:*:*:endpoint/*
            Effect: Allow
          - Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            Resource:
            - arn:aws:s3:::*
            Effect: Allow
          Version: '2012-10-17'
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"

  # ML model -- model data should be transferred from GitHub repo to S3 via
  # the backend CICD Pipeline.
  SageMakerModelChunkClassifierV2:
    Type: AWS::SageMaker::Model
    Properties: 
      ModelName: "ChunkClassifierModelV2"
      ExecutionRoleArn: !GetAtt SageMakerExecutionRole.Arn
      PrimaryContainer:
        ModelDataUrl: !Sub s3://${S3ArtifactsBucket}/SageMaker/ChunkClassification/model.tar.gz
        Image: !Sub "811284229777.dkr.ecr.${AWS::Region}.amazonaws.com/blazingtext:latest"

  SageMakerChunkClassifierEndpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointConfigName: !GetAtt SageMakerChunkClassifierEndpointConfigV2.EndpointConfigName

  SageMakerChunkClassifierEndpointConfigV2:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      EndpointConfigName: "ChunkClassifierEndpointConfigV2"
      ProductionVariants:  
      - ModelName: !GetAtt SageMakerModelChunkClassifierV2.ModelName
        VariantName: AllTraffic
        InitialInstanceCount: 1
        InstanceType: ml.t2.medium
        InitialVariantWeight: 1

  # ML model -- model data should be transferred from GitHub repo to S3 via
  # the backend CICD Pipeline.
  SageMakerModelQuestionClassifierV2:
    Type: AWS::SageMaker::Model
    Properties: 
      ModelName: "QuestionClassifierModelV2"
      ExecutionRoleArn: !GetAtt SageMakerExecutionRole.Arn
      PrimaryContainer:
        ModelDataUrl: !Sub s3://${S3ArtifactsBucket}/SageMaker/QuestionClassification/model.tar.gz
        Image: !Sub "811284229777.dkr.ecr.${AWS::Region}.amazonaws.com/blazingtext:latest"

  SageMakerQuestionClassifierEndpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointConfigName: !GetAtt SageMakerQuestionClassifierEndpointConfigV2.EndpointConfigName

  SageMakerQuestionClassifierEndpointConfigV2:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      EndpointConfigName: "QuestionClassifierEndpointConfigV2"
      ProductionVariants:  
      - ModelName: !GetAtt SageMakerModelQuestionClassifierV2.ModelName
        VariantName: AllTraffic
        InitialInstanceCount: 1
        InstanceType: ml.t2.medium
        InitialVariantWeight: 1

Outputs:
  SageMakerChunkClassifierEndpointName:
    Value: !GetAtt SageMakerChunkClassifierEndpoint.EndpointName
  SageMakerQuestionClassifierEndpointName:
    Value: !GetAtt SageMakerQuestionClassifierEndpoint.EndpointName