# cfn-master.yaml
# Author: Brian Jopling, Jan 2020
#
# Description:
#   Deploys nested templates to automate the creation of all infrastructure
#   required by StudyBuddy.
#
# Usage: - Manual validation of ACM certs must be done during the deployment process.
#           Otherwise, the stack will hang. (Two certs, one for Cognito, one for Frontend.)
#        - Upon completion of deployment, an Alias record must be created to point
#           the custom domain url to the CloudFront distribution. (Two urls, one for 
#           Cognito, one for Frontend.)
#
# Pre-requisites: Google Client ID and Client Secret must be stored in SecretsManager before deploying.
#

AWSTemplateFormatVersion: "2010-09-09"
Description: Master template for creating all StudyBuddy infra.

Parameters:
  S3InfrastructureBucket:
    Type: String
    Default: studybuddy-cfn-templates
    Description: S3 bucket containing all the CloudFormation templates & OpenAPI Spec.

Resources:
  NestedStackCognito:
   Type: AWS::CloudFormation::Stack
   Properties: 
     TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-cognito.yaml"
     TimeoutInMinutes: 30

  NestedStackRDS:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-rds.yaml"
      TimeoutInMinutes: 35

  NestedStackLambda:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters:
        EnvVarDbUrl: !GetAtt NestedStackRDS.Outputs.RDSApplicationUrl
        SageMakerChunkClassifierEndpointName: !GetAtt NestedStackSageMaker.Outputs.SageMakerChunkClassifierEndpointName
        SageMakerQuestionClassifierEndpointName: !GetAtt NestedStackSageMaker.Outputs.SageMakerQuestionClassifierEndpointName
      TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-lambda.yaml"
      TimeoutInMinutes: 10

  NestedStackApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters: 
        CognitoUserPoolArn: !GetAtt NestedStackCognito.Outputs.CognitoUserPoolArn
      TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-apigw.yaml"
      TimeoutInMinutes: 10
  
  NestedStackFrontendS3:
   Type: AWS::CloudFormation::Stack
   Properties:
     TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-frontend.yaml"
     TimeoutInMinutes: 10

  NestedStackFrontendCloudFront:
   Type: AWS::CloudFormation::Stack
   Properties:
     Parameters:
       CloudFrontOriginAccessIdentity: !GetAtt NestedStackFrontendS3.Outputs.CloudFrontOriginAccessIdentity
       S3FrontendDeployBucket: !GetAtt NestedStackFrontendS3.Outputs.S3FrontendDeployBucket
     TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-frontend.yaml"
     TimeoutInMinutes: 60
  
  NestedStackCICD:
   Type: AWS::CloudFormation::Stack
   DependsOn: 
   - NestedStackFrontendS3
   - NestedStackLambda
   Properties:
     TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-cicd.yaml"
     TimeoutInMinutes: 30

  # Needs to be created after CICD Pipelines.
  # The Backend CICD Pipeline pulls in the backend code from GitHub,
  # which includes the sqldump. The sqldump is imported into the RDS.
  NestedStackRDSImport:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - NestedStackCICD
    Properties: 
      Parameters:
        RDSEndpointAddress: !GetAtt NestedStackRDS.Outputs.RDSApplicationUrl
      TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-rds-import.yaml"
      TimeoutInMinutes: 25

  # Needs to be created after CICD Pipelines.
  # The Backend CICD Pipeline pulls in the backend code from GitHub,
  # which includes the SageMaker model data. 
  # The model data is used to construct the initial model.
  NestedStackSageMaker:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - NestedStackCICD
    Properties: 
      TemplateURL: !Sub "https://${S3InfrastructureBucket}.s3.amazonaws.com/cfn-nested-sagemaker.yaml"
      TimeoutInMinutes: 40
